### ISSUE TITLE
Failed to clone or download due to too many files or too large the repo?

### ISSUE THREAD

**Issue by II-Matto** [ShahinHonarvar/Turbulence-Benchmark#1]
The clone was interrupted, while the downloaded zip file contained only some files (but already 1.7G).

**Comment by ShahinHonarvar** [comment]
Following your comment, I downloaded the .zip file once and used the `git clone` on another occasion. In both cases, the complete repository was successfully downloaded.

Check this, this may help you:
https://stackoverflow.com/questions/48200429/not-able-to-clone-large-repo-code-on-git

**Comment by II-Matto** [comment]
After downloading the .zip file again, I still obtained an incomplete file with a size of 5.9GB. I will try the `git clone` later. Thanks.

BTW, I suggest to separate the large number of data files as packed as zip files and upload them to cloud disk rather than scattered in the Github repository.
